package issue

import (
	"fmt"
	"sort"
	"time"

	"github.com/git-bug/git-bug/entities/identity"
	"github.com/git-bug/git-bug/entity"
	"github.com/git-bug/git-bug/entity/dag"
)

var _ dag.Snapshot = &Snapshot{}

// Snapshot is a compiled form of the Issue data structure used for storage and merge.
//
// Everything here is structural, in the sense that the operation log is made of it.
// What an issue *has* lives in Fields, keyed by the schema's field keys,
// with values kept as the JSON the operations carried.
// Relations to other issues are fields too,
// whose kind says the value is an issue id (configurable-schema.md D4).
type Snapshot struct {
	id entity.Id

	Fields       map[string]Value
	Comments     []Comment
	Author       identity.Interface
	Actors       []identity.Interface
	Participants []identity.Interface
	CreateTime   time.Time

	Timeline []TimelineItem

	Operations []dag.Operation
}

// Id returns the Issue identifier
func (snap *Snapshot) Id() entity.Id {
	if snap.id == "" {
		// simply panic as it would be a coding error (no id provided at construction)
		panic("no id")
	}
	return snap.id
}

func (snap *Snapshot) AllOperations() []dag.Operation {
	return snap.Operations
}

func (snap *Snapshot) AppendOperation(op dag.Operation) {
	snap.Operations = append(snap.Operations, op)
}

// EditTime returns the last time an issue was modified
func (snap *Snapshot) EditTime() time.Time {
	if len(snap.Operations) == 0 {
		return time.Unix(0, 0)
	}

	return snap.Operations[len(snap.Operations)-1].Time()
}

// GetCreateMetadata return the creation metadata
func (snap *Snapshot) GetCreateMetadata(key string) (string, bool) {
	return snap.Operations[0].GetMetadata(key)
}

// Title returns the title field, which every valid issue has.
func (snap *Snapshot) Title() string {
	title, _ := String(snap.Fields[TitleKey])
	return title
}

// FieldString returns a field decoded as a string, and whether it is one.
func (snap *Snapshot) FieldString(key string) (string, bool) {
	v, ok := snap.Fields[key]
	if !ok {
		return "", false
	}
	return String(v)
}

// FieldKeys returns the set field keys, sorted, for deterministic output.
func (snap *Snapshot) FieldKeys() []string {
	keys := make([]string, 0, len(snap.Fields))
	for k := range snap.Fields {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// Items returns the items of a list-valued field,
// empty when the field is unset or holds something that is not a list.
func (snap *Snapshot) Items(key string) []Value {
	v, ok := snap.Fields[key]
	if !ok {
		return nil
	}
	items, _ := Items(v)
	return items
}

// HasItem reports whether a list-valued field contains the item.
func (snap *Snapshot) HasItem(key string, item Value) bool {
	return containsItem(snap.Items(key), canonical(item))
}

// SearchTimelineItem will search in the timeline for an item matching the given hash
func (snap *Snapshot) SearchTimelineItem(id entity.CombinedId) (TimelineItem, error) {
	for i := range snap.Timeline {
		if snap.Timeline[i].CombinedId() == id {
			return snap.Timeline[i], nil
		}
	}

	return nil, fmt.Errorf("timeline item not found")
}

// SearchComment will search for a comment matching the given id
func (snap *Snapshot) SearchComment(id entity.CombinedId) (*Comment, error) {
	for _, c := range snap.Comments {
		if c.combinedId == id {
			return &c, nil
		}
	}

	return nil, fmt.Errorf("comment not found")
}

// SearchCommentByOpId will search for a comment generated by the given operation Id
func (snap *Snapshot) SearchCommentByOpId(id entity.Id) (*Comment, error) {
	for _, c := range snap.Comments {
		if c.targetId == id {
			return &c, nil
		}
	}

	return nil, fmt.Errorf("comment not found")
}

// setField applies a value, where null clears.
func (snap *Snapshot) setField(key string, value Value) {
	if snap.Fields == nil {
		snap.Fields = map[string]Value{}
	}
	if IsNull(value) {
		delete(snap.Fields, key)
		return
	}
	snap.Fields[key] = value
}

// append the operation author to the actors list
func (snap *Snapshot) addActor(actor identity.Interface) {
	for _, a := range snap.Actors {
		if actor.Id() == a.Id() {
			return
		}
	}

	snap.Actors = append(snap.Actors, actor)
}

// append the operation author to the participants list
func (snap *Snapshot) addParticipant(participant identity.Interface) {
	for _, p := range snap.Participants {
		if participant.Id() == p.Id() {
			return
		}
	}

	snap.Participants = append(snap.Participants, participant)
}

// HasParticipant return true if the id is a participant
func (snap *Snapshot) HasParticipant(id entity.Id) bool {
	for _, p := range snap.Participants {
		if p.Id() == id {
			return true
		}
	}
	return false
}

// HasAnyParticipant return true if one of the ids is a participant
func (snap *Snapshot) HasAnyParticipant(ids ...entity.Id) bool {
	for _, id := range ids {
		if snap.HasParticipant(id) {
			return true
		}
	}
	return false
}

// HasActor return true if the id is a actor
func (snap *Snapshot) HasActor(id entity.Id) bool {
	for _, p := range snap.Actors {
		if p.Id() == id {
			return true
		}
	}
	return false
}

// HasAnyActor return true if one of the ids is a actor
func (snap *Snapshot) HasAnyActor(ids ...entity.Id) bool {
	for _, id := range ids {
		if snap.HasActor(id) {
			return true
		}
	}
	return false
}
